// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReactNative = require("react-native");

function Speech(Props) {
  var speech = Props.speech;
  return React.createElement(ReactNative.View, {
              children: $$Array.mapi((function (index, s) {
                      return React.createElement(ReactNative.Text, {
                                  children: s,
                                  key: String(index)
                                });
                    }), speech)
            });
}

var make = Speech;

exports.make = make;
/* react Not a pure module */
